application:
  name: @name@
  version: @version@
  description: @description@

cors:
  origin-patterns:
    - http://localhost:8080
    - http://localhost:3000
    - https://edson.com.br

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_with_kotlin?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  paths-to-match:
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true